### ISSUE TITLE
L'interface de connexion

### ISSUE THREAD

**Issue by Hlopon** [kalamu/dashboard-bundle#1]
Je cherche la page de connexion, je suppose qu'elle doit être répartie entre différents bout de code ?

**Comment by nykopol** [comment]
Il n'y a pas d'interface de connexion. Ce bundle est complètement indépendant de la logique de sécurité d'une application.

For English readers, the question is:

> I'm looking for the connexion page, I guess that it must be on some different part of the code?

The response is:

> There is no connexion page as the bundle is independent of the security system of the application.

**Comment by Hlopon** [comment]
En fait je voudrais refondre l'interface pour la faire correspondre à l'image que je vous ai envoyé par mail (version mobile et tablette).
![kalamu_presentation_v3_roho_modern-digital-tech-device-collection](https://user-images.githubusercontent.com/26056073/27179275-8762288c-51d6-11e7-8e8a-513981d44fca.png)
